---
abstract: 'Data::Dumper, sweetened with Devel::Declare'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.61
  Test::Warn: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Dumper::Declare
name: Data-Dumper-Declare
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  B::Hooks::EndOfScope: 0.09
  Devel::Assert: 0
  Devel::Declare: 0.006007
  Devel::Declare::Context::Simple: 0
  PPI: 0
  Sub::Exporter: 0
  Sub::Install: 0.925
  namespace::clean: 0.19
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Data-Dumper-Declare
  homepage: https://metacpan.org/release/Data-Dumper-Declare
  license: http://dev.perl.org/licenses/
version: 0.001
