# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/Data-Dumper-Declare/project>
	:perl_version_from _:main;
	:version_from _:main;
	:readme_from _:main;
	:requires
		"Devel::Declare 0.006007",
		"Devel::Declare::Context::Simple",
		"B::Hooks::EndOfScope 0.09",
		"Sub::Install 0.925",
		"Sub::Exporter",
		"namespace::clean 0.19",
		"PPI",
		"Devel::Assert";
	:test_requires
		"Test::More 0.61",
		"Test::Warn",
		"Test::Exception".

_:main
	<http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#fileName> "lib/Data/Dumper/Declare.pm".

